[project]
name = 'Real-Estate-Fractional-Platform'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.property-valuation-oracle]
path = 'contracts/property-valuation-oracle.clar'
clarity_version = 3
epoch = '3.2'

[contracts.rental-income-distributor]
path = 'contracts/rental-income-distributor.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
